AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  isi-bible-verse-devo-gpt

  Sample SAM Template for isi-bible-verse-devo-gpt

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 512

Resources:
  ISIBibleVerseDevoGPTFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: isi_bible_verse_devo_gpt/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonSSMReadOnlyAccess
      - Statement:
            - Effect: Allow
              Action: kms:Decrypt
              Resource: arn:aws:kms:us-east-1:054619787751:key/09ab41da-2847-4fc9-9795-58b2f73b66b5
  ISIBibleVerseDevoGPTFunctionLogGroup:
      Type: AWS::Logs::LogGroup
      DeletionPolicy: Retain
      UpdateReplacePolicy: Delete
      Properties:
        LogGroupName: !Sub /aws/lambda/${ISIBibleVerseDevoGPTFunction}
  ISIBibleVerseDevoGPTFunctionScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      ScheduleExpression: cron(00 14 * * ? *)
      FlexibleTimeWindow:
        Mode: FLEXIBLE
        MaximumWindowInMinutes: 1
      Target:
        Arn: !GetAtt ISIBibleVerseDevoGPTFunction.Arn
        RoleArn: !GetAtt ISIBibleVerseDevoGPTFunctionSchedulerToISIBibleVerseDevoGPTFunctionRole.Arn
  ISIBibleVerseDevoGPTFunctionSchedulerToISIBibleVerseDevoGPTFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: !Sub scheduler.${AWS::URLSuffix}
          Action: sts:AssumeRole
          Condition:
            ArnLike:
              aws:SourceArn: !Sub
                - arn:${AWS::Partition}:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/*/${AWS::StackName}-${ResourceId}-*
                - ResourceId: ISIBibleVerseDevoGPTFunctionScheduler
      Policies:
        - PolicyName: StartExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt ISIBibleVerseDevoGPTFunction.Arn